#!/usr/bin/env ruby

$LOAD_PATH.unshift(File.join(File.dirname(__FILE__), "..", "lib"))

require "dotfiles"

begin
  require "highline/import"
rescue LoadError
  abort "You have to install highline at first!"
end

def name
  @name ||= ask("[Git Setup] Your name: ")
end

def email
  @email ||= ask("[Git Setup] Your email: ")
end

sh "git config --global user.name '#{name}'"
sh "git config --global user.email '#{email}'"
