require "rake/clean"

dotvim   = File.join(ENV["HOME"], ".vim")
dotvimrc = File.join(ENV["HOME"], ".vimrc")

CLEAN.include("*.patch")

desc "Build dotfiles and copy them to the $HOME directory"
task :install => ["install:vimrc", "install:vim"]

namespace :install do
  task :vim => :clean do
    puts "Installing ~/.vim ..."
    rm_rf "#{ENV["HOME"]}/.vim"
    cp_r "vim", "#{ENV["HOME"]}/.vim"
  end

  task :vimrc => [:clean, "patch:generate"] do
    puts "Installing ~/.vimrc ..."
    cp "vimrc", "#{dotvimrc}-#{Time.now.strftime("%m%d%H%S")}" # the clean generated vimrc without changes added by merge
    cp "vimrc", dotvimrc
    Rake::Task["patch:apply"].invoke
    if File.exist?("changes.patch")
      puts "\n\n=== Diff ==="
      puts File.read("changes.patch")
    end
  end
end

namespace :patch do
  task :generate do
    puts "Generating patch ..."
    versions = Dir["#{ENV["HOME"]}/.vimrc-*"]
    previous = versions.sort.last
    if previous
      sh "diff #{previous} #{ENV["HOME"]}/.vimrc > changes.patch; true"
    end
  end

  desc "Merge changes made in ~/.vimrc back into generated vimrc"
  task :apply do
    puts "Applying patch ..."
    versions = Dir["#{ENV["HOME"]}/.vimrc-*"] || Array.new
    previous = versions.sort[-2]
    if previous
      p sh("patch #{ENV["HOME"]}/.vimrc changes.patch")
    end
  end
end

task :vimball => ["vimball:install", "vimball:merge"]
namespace :vimball do
  task :install do
    if ENV["VIMBALL"].nil?
      abort "You have to setup VIMBALL environment variable first!"
    end
    rm_rf File.join(ENV["HOME"], ".vim")
    sh "vim -e -c 'source #{ENV["VIMBALL"]}'"
  end

  task :merge do
    require "find"
    Find.find(File.join(ENV["HOME"], ".vim")) do |file|
      next if File.directory?(file)
      original = file.dup
      file[ENV["HOME"] + "/."] = ""
      mkdir_p(File.dirname(file)) unless File.directory?(File.dirname(file))
      if File.exist?(file)
        puts "Warning: appending to #{file}"
        File.open(file, "a") do |file|
          file.puts(File.read(original))
        end
      else
        mv original, file
      end
      rm_rf File.join(ENV["HOME"], ".vim")
    end
  end
end
