$LOAD_PATH.unshift(File.join(File.dirname(__FILE__), "..", "lib"))

require "rake/clean"
require "dotfiles/tasks"

CLEAN.include("*.patch")

FILES  = FileList["vimrc", "vim/**/*"]
BACKUP = FileList["vimrc"]

# regenerate tags file
task :tags do
  Dir.chdir("vim/doc") do
    sh "ctags *"
  end
end

task :vimball => ["vimball:install", "vimball:merge"]
namespace :vimball do
  task :install do
    if ENV["VIMBALL"].nil?
      abort "You have to setup VIMBALL environment variable first!"
    end
    rm_rf File.join(ENV["HOME"], ".vim")
    sh "vim -e -c 'source #{ENV["VIMBALL"]}'"
  end

  task :merge do
    require "find"
    Find.find(File.join(ENV["HOME"], ".vim")) do |file|
      next if File.directory?(file)
      original = file.dup
      file[ENV["HOME"] + "/."] = ""
      mkdir_p(File.dirname(file)) unless File.directory?(File.dirname(file))
      if File.exist?(file)
        puts "Warning: appending to #{file}"
        File.open(file, "a") do |file|
          file.puts(File.read(original))
        end
      else
        mv original, file
      end
      rm_rf File.join(ENV["HOME"], ".vim")
    end
  end
end

# register tag regeneration
task :install => "tags"