$LOAD_PATH.unshift(File.join(File.dirname(__FILE__), "..", "lib"))

require "pathname"
require "rake/clean"
require "dotfiles/tasks"

CLEAN.include("zshrc", "*.patch")

NAME   = "zsh"
FILES  = FileList["zshrc"]
BACKUP = FileList["zshrc"]

# === Helpers === #
def relative_path(file)
  file = Pathname.new(File.expand_path(file))
  current = Pathname.new(File.expand_path(Dir.pwd))
  file.relative_path_from(current)
end

# === Tasks === #
desc "Build all the files to the one big zshrc"
file "zshrc" => (FileList["**/*.sh"] - ["zshrc"]) do
  puts "Generating zshrc ..."
  files = FileList["{setup,functions,aliases,completion,environment,prompt}/**/*.sh"]
  if File.exist?("platforms/#{platform}.sh")
    files.push "platforms/#{platform}.sh"
  else
    warn "There is no platform file for you platform (expected platforms/#{platform}.sh)"
  end
  File.open("zshrc", "w") do |output|
    output.puts("source /etc/profile\n\n")
    files.each do |file|
      filename = relative_path(file)
      output.puts("### #{filename.to_s.upcase} ###")
      output.puts(File.read(file))
      output.puts
    end
  end
end

# register zshrc generation
task :preinstall => "zshrc"
